---

igp:
  loopbacks:
    ipv4:
      local_ip: 10.200.0.3
      netmask: 32
    ipv6:
      local_ip: fd00:1::3
      netmask: 128
  neighbors:
  - interface: Ethernet1
    peer: vqfx1
    ipv4:
      local_ip: 10.0.0.1
      netmask: 31
    ipv6:
      local_ip: fd00:1:1::1
      netmask: 127
  - interface: Ethernet2
    peer: veos4
    ipv4:
      local_ip: 10.0.0.6
      netmask: 31
    ipv6:
      local_ip: fd00:1:1::6
      netmask: 127

