---

- name: Transit configuration - Juniper
  template:
    src={{ item }}.j2
    dest={{ config_dir }}/{{ ansible_host }}/3_{{ ansible_loop.index }}_{{ item }}.part
  tags:
    - transit
  when: 
    - "'juniper' in group_names"  
  loop:
    - interfaces-juniper.conf
    - bgp-juniper.conf
    - policies-juniper.conf
  loop_control:
    extended: yes

- name: Transit configuration - Arista
  template:
    src={{ item }}.j2
    dest={{ config_dir }}/{{ ansible_host }}/3_{{ ansible_loop.index }}_{{ item }}.part
  tags:
    - transit
  when: 
    - "'arista' in group_names"  
  loop:
    - interfaces-arista.conf
    - bgp-arista.conf
    - policies-arista.conf
  loop_control:
    extended: yes