---

- name: Check if directory config is present
  file: path={{ config_dir }} state=directory

- name: Clean device config path
  file:
    state: "{{ item }}"
    path: "{{ config_dir }}/{{ ansible_host }}"
    owner: "{{ config_owner }}"
    group: "{{ config_group }}"
  with_items:
    - absent
    - directory
