---
# tasks file for roles/base

- name: Create host specific configuration directory
  file: path=~/configs/{{ ansible_host }} state=directory

- file: path=~/configs/{{ ansible_host }}/igp.conf.part state=absent
- file: path=~/configs/{{ ansible_host }}/ospf.conf.part state=absent
- file: path=~/configs/{{ ansible_host }}/{{ ansible_host }}.conf state=absent

- name: IGP Configuration - Juniper
  template:
    src={{ item }}.j2
    dest=~/configs/{{ ansible_host }}/{{ item }}.part
  tags:
    - igp
  when: "'juniper' in group_names"  
  with_items:
    - igp-juniper.conf

- name: OSPF Configuration - Juniper
  template:
    src={{ item }}.j2
    dest=~/configs/{{ ansible_host }}/{{ item }}.part
  tags:
    - ospf
  when: "'juniper' in group_names"  
  with_items:
    - ospf-juniper.conf

- name: IGP Configuration - Arista
  template:
    src={{ item }}.j2
    dest=~/configs/{{ ansible_host }}/{{ item }}.part
  tags:
    - igp
  when: "'arista' in group_names"  
  with_items:
    - igp-arista.conf

- name: OSPF Configuration - Arista
  template:
    src={{ item }}.j2
    dest=~/configs/{{ ansible_host }}/{{ item }}.part
  tags:
    - ospf
  when: "'arista' in group_names"  
  with_items:
    - ospf-arista.conf