---

- name: IGP configuration - Juniper
  template:
    src={{ item }}.j2
    dest={{ config_dir }}/{{ ansible_host }}/1_{{ ansible_loop.index }}_{{ item }}.part
  tags:
    - igp
  when: 
    - "'juniper' in group_names"  
  loop:
    - interfaces-juniper.conf
    - ospf-juniper.conf
  loop_control:
    extended: yes

- name: IGP configuration - Arista
  template:
    src={{ item }}.j2
    dest={{ config_dir }}/{{ ansible_host }}/1_{{ ansible_loop.index }}_{{ item }}.part
  tags:
    - igp
  when: 
    - "'arista' in group_names"  
  loop:
    - interfaces-arista.conf
    - ospf-arista.conf
  loop_control:
    extended: yes
