---

interfaces:
  - name: eth1
    ipv4: 
      ip: 10.1.99.6
      netmask: 31
    ipv6:
      ip: fd00:1::6
      netmask: 127 
loopback:
  ipv4: 
    ip: 10.133.9.30
    netmask: 24
  ipv6:
    ip: "fddd::133:930"
    netmask: 64
bgp:
  id: 10.133.9.30
  asn: 33930
  sessions:
    ipv4:
      - peer_ip: 10.1.99.7
        peer_asn: 65501
    ipv6:
      - peer_ip: fd00:1::7
        peer_asn: 65501