
data_sources: # --------------------------------------------------------
  NetboxLab:
    type: netbox_api
    args:
      url: http://ks01.commit.ninja:32776/
      token: 0123456789abcdef0123456789abcdef01234567

  Sessions:
    type: file
    args:
      path: sessions.yaml
      content_type: yaml

data_sets: # --------------------------------------------------------
  - name: sessions
    from: source
    args:
      name: Sessions
      filter: .[]

  - name: site_info
    from: source
    args:
      name: NetboxLab
      app: dcim
      type: sites

  - name: raw_ips
    from: source
    args:
      name: NetboxLab
      app: ipam
      type: ip-addresses


  - name: nb_devices
    from: source
    args:
      name: NetboxLab
      app: dcim
      type: devices

  - name: ips
    from: filtering
    args:
      name: raw_ips
      filter: '[.[] | {id: .id, address: .address, intf_id: .interface.id, family: .family}]'
  - name: interfaces
    from: filtering
    args:
      name: raw_ips
      filter: '[.[] | .interface | {id: .id, name: .name, dev_id: .device.id}] | unique'

  - name: devices
    from: filtering
    args:
      name: raw_ips
      filter: '[.[] | .interface.device | {name: .name, id: .id}] | unique'


  - name: full_interfaces
    from: decoration
    args:
      main:
        name: interfaces
        pivot: .id
      decorators:
        - name: ips
          pivot: .intf_id
          anchor: ip

  - name: full_devices
    from: merge
    args:
      sets:
        - name: devices
          pivot: .id
        - name: nb_devices
          pivot: .id

  - name: decorated_devices
    from: decoration
    args:
      main:
        name: full_devices
        pivot: .id
      decorators:
        - name: full_interfaces
          pivot: .dev_id
          anchor: interfaces

  - name: final_devices
    from: merge
    args:
      sets:
        - name: decorated_devices
          pivot: .primary_ip4.address | split("/") | .[0]
        - name: sessions
          pivot: .id

  - name: full_site_info
    from: filtering
    args:
      name: site_info
      filter: ".[0] | {local: {asn: .asn, physical_address: .physical_address}}"

render: # --------------------------------------------------------
  elements:
    - name: final_devices
      args:
        index:
          value: .name
        host_vars:
          bgp: .bgp
          loopback: '{
            ipv4: .primary_ip4.address | split("/") | {address: .[0], netmask: .[1]},
            ipv6: .primary_ip6.address | split("/") | {address: .[0], netmask: .[1]},
          }'
          name: .name
          tenant: .tenant.name
          interfaces: '[ .interfaces[] | {
            name: .name,
            ipv4: [.ip[] | select(.family.value == 4) | .address | split("/") | {address: .[0], netmask: .[1]}][0],
            ipv6: [.ip[] | select(.family.value == 6) | .address | split("/") | {address: .[0], netmask: .[1]}][0]
          }]'
  group_vars:
    - group: final_devices
      set: full_site_info
