igp:
  loopbacks:
  - ipv4:
      local_ip: 10.200.0.3
      netmask: 32
    name: lo0
    vlan: 0
  neighbors:
  - interface: Ethernet1
    peer: vqfx1
    speed: 10G
    type: local-core
    vlans:
    - id: 0
      ipv4:
        local_ip: 192.168.2.2
        netmask: 24
        peer_ip: 192.168.2.1
  - interface: Ethernet2
    peer: veos4
    speed: 10G
    type: local-core
    vlans:
    - id: 0
      ipv4:
        local_ip: 192.168.5.1
        netmask: 24
        peer_ip: 192.168.5.2
