---

- name: iBGP configuration - Juniper
  template:
    src={{ item }}.j2
    dest={{ config_dir }}/{{ ansible_host }}/2_{{ ansible_loop.index }}_{{ item }}.part
  tags:
    - ibgp
  when: 
    - "'juniper' in group_names"  
  loop:
    - bgp-juniper.conf
    - policies-juniper.conf
  loop_control:
    extended: yes

- name: iBGP configuration - Arista
  template:
    src={{ item }}.j2
    dest={{ config_dir }}/{{ ansible_host }}/2_{{ ansible_loop.index }}_{{ item }}.part
  tags:
    - ibgp
  when: 
    - "'arista' in group_names"  
  loop:
    - bgp-arista.conf
    - policies-arista.conf
  loop_control:
    extended: yes
