ansible_connection: network_cli
ansible_network_os: eos
ansible_user: admin
ansible_ssh_pass: admin
ansible_become: yes
ansible_become_method: enable


arista_credentials:
  username: admin
  password: admin
  transport: cli