igp:
  loopbacks:
  - ipv4:
      local_ip: 10.200.0.1
      netmask: 32
    name: lo0
    vlan: 0
  neighbors:
  - interface: xe-0/0/0
    peer: veos3
    speed: 10G
    type: local-core
    vlans:
    - id: 0
      ipv4:
        local_ip: 10.0.0.0
        netmask: 31
        peer_ip: 10.0.0.1
  - interface: xe-0/0/1
    peer: vqfx2
    speed: 10G
    type: local-core
    vlans:
    - id: 0
      ipv4:
        local_ip: 10.0.0.2
        netmask: 31
        peer_ip: 10.0.0.3
