---

transit_interfaces:
- name: xe-0/0/2
  cid: ID-1
  peer_name: Transit 1
  ipv4:
    local_ip: 10.1.99.1
    netmask: 31
    peer_ip: 10.1.99.0
  ipv6:
    local_ip: fdaa:1::1
    netmask: 127
    peer_ip: fdaa:1::0
- name: xe-0/0/3
  cid: ID-2
  peer_name: Transit 2
  ipv4:
    local_ip: 10.1.99.3
    netmask: 31
    peer_ip: 10.1.99.2
  ipv6:
    local_ip: fdaa:1::3
    netmask: 127
    peer_ip: fdaa:1::2

transit_sessions:
- name: Transit 1
  peer_asn: 35085
  ipv4:
    peer_ip: 10.1.99.0
  ipv6:
    peer_ip: fdaa:1::0
- name: Transit 2
  peer_asn: 33930
  ipv4:
    peer_ip: 10.1.99.2
  ipv6:
    peer_ip: fdaa:1::2
