igp:
  loopbacks:
  - ipv4:
      local_ip: 10.200.0.4
      netmask: 32
    name: lo0
    vlan: 0
  neighbors:
  - interface: Ethernet1
    peer: vqfx2
    speed: 10G
    type: local-core
    vlans:
    - id: 0
      ipv4:
        local_ip: 10.0.0.5
        netmask: 31
        peer_ip: 10.0.0.4
  - interface: Ethernet2
    peer: veos3
    speed: 10G
    type: local-core
    vlans:
    - id: 0
      ipv4:
        local_ip: 10.0.0.7
        netmask: 31
        peer_ip: 10.0.0.6
