---

igp:
  loopbacks:
    ipv4:
      local_ip: 10.200.0.4
      netmask: 32
    ipv6:
      local_ip: fd00:1::4
      netmask: 128
  neighbors:
  - interface: Ethernet1
    peer: vqfx2
    ipv4:
      local_ip: 10.0.0.5
      netmask: 31
    ipv6:
      local_ip: fd00:1:1::5
      netmask: 127
  - interface: Ethernet2
    peer: veos3
    ipv4:
      local_ip: 10.0.0.7
      netmask: 31
    ipv6:
      local_ip: fd00:1:1::7
      netmask: 127

