---
# tasks file for roles/base

- name: Base Configuration - Juniper
  template:
    src={{ item }}.j2
    dest={{ config_dir }}/{{ ansible_host }}/0_{{ ansible_loop.index }}_{{ item }}.part
  tags:
    - base
  when: 
    - "'juniper' in group_names" 
  with_items:
    - base-juniper.conf
    - users-juniper.conf
  loop_control:
    extended: yes

- name: Base Configuration - Arista
  template:
    src={{ item }}.j2
    dest={{ config_dir }}/{{ ansible_host }}/0_{{ ansible_loop.index }}_{{ item }}.part
  tags:
    - base
  when: 
    - "'arista' in group_names" 
  with_items:
    - base-arista.conf
    - users-arista.conf
  loop_control:
    extended: yes