---
# tasks file for roles/base

- name: Base Configuration - Juniper
  template:
    src={{ item }}.j2
    dest=~/configs/{{ ansible_host }}/{{ item }}.part
  tags:
    - base
  when: 
    - "'juniper' in group_names" 
  with_items:
    - base-juniper.conf
    - users-juniper.conf

- name: Base Configuration - Arista
  template:
    src={{ item }}.j2
    dest=~/configs/{{ ansible_host }}/{{ item }}.part
  tags:
    - base
  when: 
    - "'arista' in group_names" 
  with_items:
    - base-arista.conf
    - users-arista.conf