---

- name: CleanUp
  hosts: all
  connection: local
  tags:
    - always
  gather_facts: no
  tasks:
    - name: Remove if exist the temporary configuration directory
      file: path={{ config_dir }}/{{ ansible_host }} state=absent
    - name: Remove if exist the configuration file
      file: path={{ config_dir }}/{{ ansible_host }}.conf state=absent
    - name: Create the configuration directory
      file: path={{ config_dir }}/{{ ansible_host }} state=directory

- name: Config 
  hosts: all
  connection: network_cli
  gather_facts: no
  roles:
    # Juniper role for Ansible 
    - Juniper.junos
    # Basic configuration
    - base
    # IGP
    - igp
    # IBGP
    - ibgp
    # Transit configuration
    - transit

- name: Enhance configuration
  hosts: all
  connection: local
  tags:
    - always
  gather_facts: no
  tasks:
    - name: Assembling configurations and copying to conf
      assemble: src={{ config_dir }}/{{ ansible_host }}/ dest={{ config_dir }}/{{ ansible_host }}.conf

- name: Connection to Arista devices
  hosts: arista
  connection: local
  tags:
    - always
  gather_facts: no
  tasks:
    - napalm_install_config:
        hostname : "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        dev_os: "{{ ansible_network_os }}"
        password : "{{ ansible_password }}"
        config_file: "{{ config_dir }}/{{ inventory_hostname }}.conf"
        commit_changes: true
        replace_config: true
        get_diffs: true
        diff_file : "{{ config_dir }}/{{ inventory_hostname }}/diff"
      register: response_arista
    - name: Print the difference if exists
      tags: always
      debug:
        var: response_arista
      when: response_arista is defined and response_juniper.diff_lines is defined

- name: Connection to Juniper devices
  hosts: juniper
  connection: local
  tags:
    - always
  gather_facts: no
  tasks:
    - name: Pushing config ... please wait ...
      juniper_junos_config:
        config_mode: 'private'
        src: "{{ config_dir }}/{{ inventory_hostname }}.conf"
        load: overwrite
        ignore_warning: true
      register: response_juniper
    - name: Print the difference if exists
      tags: always
      debug:
        var: response_juniper.diff_lines
      when: response_juniper is defined and response_juniper.diff_lines is defined
